language: rust
cache: cargo

rust:
  - nightly

before_install:
  # hot fix for https://github.com/ggez/ggez/issues/100
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev;
    fi

matrix:
  include:
    # Linux 64bit
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

install:
  - rustup self update
  - rustup target add $TARGET; true

script:
  - source ./ci/install_cargo_web.sh
  - cargo build --target $TARGET --verbose
  - cargo build --target $TARGET --verbose --examples
  - cargo web build --examples basic 
  - cargo web build --examples boxes
  - cargo web build --examples framebuffer
  - cargo web build --examples meshobj
  - cargo web build --examples postprocessing
  - cargo web build --examples scenenodes
  - cargo web build --examples shadow
  - cargo web build --examples skybox
  - cargo web build --examples sound
  - cargo web build --examples sponza
  - cargo web build --examples basic --release
