language: rust
cache: cargo

rust:
  - nightly

before_install:
  # hot fix for https://github.com/ggez/ggez/issues/100
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev;
    fi

matrix:
  include:
    # Linux 64bit
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

install:
  - rustup self update
  - rustup target add $TARGET; true

script:
  - cargo build --target $TARGET --verbose
  - cargo build --target $TARGET --verbose --examples