[package]
name = "unigame"
version = "0.1.0"
authors = ["Edwin Cheng <edwin0cheng@gmail.com>"]

[dependencies]
nalgebra   = "0.13"
nphysics3d = "0.7.2"
ncollide = "0.13.0"
webgl = {path="webgl"}
uni-app = {path="uni-app"}
uni-glsl = {path="uni-glsl"}
futures = "0.1"
tobj = "0.1.6"
# Bring in stdweb to make sure the main function will translate to js
stdweb =  "0.4.0"

[dependencies.lazy_static]
version = "1.0"
features = ["nightly"]

# Image related dependencies
[dependencies.image]
version = "*"
default-features = false
features = ["png_codec"]

[lib]
name = "unigame"
path = "src/lib.rs"

[[bin]]
name = "unigame-demo"
path = "src/bin/main.rs"

[replace]
"rand:0.3.20" = { path = "wasm-rand" }
"rustc-serialize:0.3.24" = { path = "wasm-rustc-serialize" }

# wasm compilation isn't currently compatible with incremental compilation
# see https://github.com/rust-lang/rust/issues/47643
[profile.dev]
incremental = false