[package]
name = "uni-app"
version = "0.1.0"
authors = ["Edwin Cheng <edwin0cheng@gmail.com>"]

[dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]
stdweb =  "0.4.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.13.0"
time = "0.1.39"

