[package]
name = "webgl"
version = "0.1.0"
authors = ["Edwin Cheng <edwin0cheng@gmail.com>"]

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gl = "0.6.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
glenum = { git = "https://github.com/oussama/glenum-rs.git" }
stdweb =  { git = "https://github.com/koute/stdweb.git" }

# wasm compilation isn't currently compatible with incremental compilation
# see https://github.com/rust-lang/rust/issues/47643
# [profile.dev]
# incremental = false
